### ISSUE TITLE
Add Sound Control to Lightbox

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#105]
Current lightbox design does not include a sound control
https://mashable.com/2018/02/13/reels-guide-to-black-panther.amp
The Black Panther example has a sound on/off control icon you can click to turn sound on or off. 
![image](https://user-images.githubusercontent.com/5694308/65654190-2ed9cd80-e042-11e9-8942-19b3ac009e73.png)
![image](https://user-images.githubusercontent.com/5694308/65654198-34371800-e042-11e9-905c-9d8f1bc1391a.png)

Add a clickable on/off sound control to the lightbox in the same location as the example from black panther 

Also add an equilizer like black panther does that only shows up if there is sound for the video
![image](https://user-images.githubusercontent.com/5694308/65656714-060a0600-e04b-11e9-9919-fbefd95ff74d.png)

**Comment by paulchrisluke** [comment]
Is there another way to tell if the video has sound or not? the bars should only be there if the video has sound

**Comment by mort3za** [comment]
Seems there are some ways to detect it, will do.
