### ISSUE TITLE
Story Order in Lightbox

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#106]
In our lightbox right now, when you click any of the tents here 
![image](https://user-images.githubusercontent.com/5694308/65654359-b58eaa80-e042-11e9-96f6-362c1db30355.png)
It will show you a series of stories, one from each tent in the order shown in the page, starting with the one you click on.  
![image](https://user-images.githubusercontent.com/5694308/65654320-92fc9180-e042-11e9-99d1-ceb6f76f5efb.png)

What we want is, when you click on a story cover, for example "First Lady Jackie Kennedy's Tent", the lightbox opens up and shows all stories related only to "First Lady Jackie Kennedy's Tent" and not any other tent's stories. There should be a series of stories in the database for each tent, activity, food and drink, etc.

**Comment by mort3za** [comment]
> What we want is, when you click on a story cover, for example "First Lady Jackie Kennedy's Tent", the lightbox opens up and shows all stories related only to "First Lady Jackie Kennedy's Tent" and not any other tent's stories. There should be a series of stories in the database for each tent, activity, food and drink, etc.


@atharva3010 Do you know how to get related stories of a story?

**Comment by paulchrisluke** [comment]
@mort3za sorry "related" was probably the wrong word. All story cards that are assigned to a single page id... but I am just now looking at the api call here and noticed we are missing an assigned page id:
https://stagingapi.whynot.earth/api/v0/pages/slug/shintamaniwild/Wild-tents

@StrangeWill is it possible to have `PageId` shown in the api? Or should we use a different cell like call to action? I'm basically trying to group stories.

**Comment by StrangeWill** [comment]
@paulchrisluke `id` on that API response is the Page ID

**Comment by paulchrisluke** [comment]
@mort3za you'd group them by `id` in that case
