### ISSUE TITLE
Fade background "doodle" images in as page scrolls.

### ISSUE THREAD

**Issue by mort3za** [whynotearth/shinta-mani-wild#113]
from #38  
https://stagingapi.whynot.earth/api/v0/pages/slug/shintamaniwild/background-images

**Comment by paulchrisluke** [comment]
lower opacity to 80% 
2x larger in size (are they showing full width right now? if so we can get larger images)
ease in only top to bottom 
slow down ease transition to very slow
Image layer should remain fixed to give parallax type feel... the background images should be scroling at a slightly different rate than the site

the fade effect should be slow like this site, (except animating from top to bottom)
https://www.discoveroutpost.com/case-studies/bear-grylls

Another explainer video dropped in discord: 
https://photos.app.goo.gl/XBA7eanbieofS7wH8

**Comment by mort3za** [comment]
No, it's resized now. Then I'll show the original size.

**Comment by mort3za** [comment]
Some of the image URLs return 404. for example this URL:  
https://res.cloudinary.com/ddwsbpkzk/image/upload/v1568018866/Shinta%20Mani%20Wild/Background/About_SMW_s2nue2.png

**Comment by paulchrisluke** [comment]
I fixed that one url, let me know which ones are still 404.
Opacity is better now but the animation is still too fast, can you slow that down too? The last two images on the pages seem to be fixed too, so it doesn't have any animations at all. 
![image](https://user-images.githubusercontent.com/5694308/66177168-9ae3b380-e68a-11e9-8164-a508023babf3.png)

**Comment by mort3za** [comment]
This one is better to be removed https://res.cloudinary.com/ddwsbpkzk/image/upload/v1570078823/Shinta%20Mani%20Wild/Background/Tigers1-fill_pm6qto.png (is similar to https://res.cloudinary.com/ddwsbpkzk/image/upload/v1570078823/Shinta%20Mani%20Wild/Background/Tigers1_onvcoh.png)

404: https://res.cloudinary.com/ddwsbpkzk/image/upload/v1568018869/Shinta%20Mani%20Wild/Background/Ladys_Portrait_wth2hc.png
