### ISSUE TITLE
Quote bubble

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#115]
Replace all quote bubbles with dog on current site
![image](https://user-images.githubusercontent.com/5694308/65929708-54dde400-e42d-11e9-84e6-1c88251a7c65.png)

To the new quote bubble design 
![image](https://user-images.githubusercontent.com/5694308/65929734-67f0b400-e42d-11e9-80e5-e188fd302927.png)
With the quote font(Roboto Thin Italic 24px) left aligned and the name of the person/publication (Roboto Bold 20px) right aligned 

New quote card available here 
https://res.cloudinary.com/ddwsbpkzk/image/upload/v1569896790/Shinta%20Mani%20Wild/general/quote_bubble_tywbfd.png

**Comment by mort3za** [comment]
I prefer to have images of the card separately, this way the card can be responsive.  
1. birds
2. line 1
3. line 2
every line can be a 1px width SVG and be repeated in the x-axis.
