### ISSUE TITLE
External/Internal Galleries

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#116]
We have external and internal galleries for each tent group (wild, waterfall, 2 bed) 
![image](https://user-images.githubusercontent.com/5694308/65929991-54921880-e42e-11e9-92ec-b6bb363bfb61.png)

We need to link this up to a gallery of images, available in the database as order number 3 (external) and order number 4 (internal) within their repective page ID's on the images sheet
![image](https://user-images.githubusercontent.com/5694308/65930201-1c3f0a00-e42f-11e9-8b28-fa3a5c9b5c55.png)

Use the same style as story lightbox but just adapt to landscape image sizes
![image](https://user-images.githubusercontent.com/5694308/65930133-dd10b900-e42e-11e9-91e9-7e24ab6a7542.png)

**Comment by mort3za** [comment]
Images should be 16:9 in the images gallery or at least be in landscape mode then I can auto-crop them by Cloudinary API.

**Comment by paulchrisluke** [comment]
images are reuploaded, they're fine now @mort3za
