### ISSUE TITLE
Link "book now" buttons to cloudbeds

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#121]
Hyperlink all "book now" buttons to cloudbeds
https://hotels.cloudbeds.com/reservation/pbZiT1#checkin=2019-10-02&checkout=2019-10-05

**Comment by mort3za** [comment]
@paulchrisluke I changed some of the links but those which are inside the full-width banner should be changed from database, "ctaLink" property.

**Comment by mort3za** [comment]
The date part of the url should be removed. Cloudbeds automatically adds it.  
https://hotels.cloudbeds.com/reservation/pbZiT1
