### ISSUE TITLE
Remove Gallery Thumbnail from Gallery

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#163]
Some of the images included in the tent galleries right now or sized incorrectly because they are meant for the gallery thumbnail, so there is a spacing issue with some of the images 
![image](https://user-images.githubusercontent.com/5694308/66298594-40fa1c80-e91c-11e9-9442-30f2fc8ba2c4.png)

Remove all image meant for the gallery thumbnails within the galleries

These images should have an "order" of 1 or 2 within their pages designating them as thumbnail images within the api 
![image](https://user-images.githubusercontent.com/5694308/66299059-faf18880-e91c-11e9-9974-874531ddd111.png)

**Comment by paulchrisluke** [comment]
![image](https://user-images.githubusercontent.com/5694308/67194236-e7681680-f420-11e9-852a-6eea0335a81f.png)
![image](https://user-images.githubusercontent.com/5694308/67194295-0666a880-f421-11e9-8fc5-25b6075c04eb.png)
![image](https://user-images.githubusercontent.com/5694308/67194318-12526a80-f421-11e9-8e20-7e4051f89bd5.png)

the gallery thumbnail images are order 1 and 2 in the databse, but they're still showing up within the gallery

**Comment by mort3za** [comment]
Checked again, seems there are two similar images, for example in wild tents:  
order 3 (visible in slider): https://res.cloudinary.com/ddwsbpkzk/image/upload/v1568014910/Shinta%20Mani%20Wild/Wild%20Tent/Wild%20Gallery/External/Exterior_Gallery_-_Wild_Tents_Gallery_4_etw67o.jpg  
order 1 (not visible in slider): https://res.cloudinary.com/ddwsbpkzk/image/upload/v1567753990/Shinta%20Mani%20Wild/Wild%20Tent/Wild_Tent_Exterior-_Tent_Page_Shinta_Mani_Wild_jzoo9m.jpg  

the first one has an incorrect ratio and should be fixed.

**Comment by paulchrisluke** [comment]
I fixed them all in the database, they should be ok now
