### ISSUE TITLE
gallery 2 images (1.5h)

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#17]
Chris: on click open a full page image gallery... something like @bamboochow maybe we can design this

**Comment by paulchrisluke** [comment]
can the image for each of these cards come from the featured image of the hyperlinked page?

ie, that image should pull the featured image of /wild-tents/ and /waterfall-tents/ (actual pages).

Also rounded corner issue:

![image](https://user-images.githubusercontent.com/5694308/63486618-79f84200-c4d2-11e9-8b4c-90264674c6dc.png)

**Comment by mort3za** [comment]
@paulchrisluke  Yeah, absolutely will. I put there those images temporarily because I didn't have actual images.  
I'll add swagger to axios library today and get images and texts from API
