### ISSUE TITLE
Add Mobile "swipe up" to pages

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#171]
Figma file: https://www.figma.com/file/SiFZE7hhRKx2fWmrfZ3uy2RO/Shinta-Mani-Wild?node-id=394%3A3753

Current mobile page starts with a full screen header image 
![image](https://user-images.githubusercontent.com/5694308/66377309-89c4da80-e9db-11e9-9716-b4b3eb3f1a03.png)

Add a "swipe up" icon to mobile pages 
![image](https://user-images.githubusercontent.com/5694308/66378052-e70d5b80-e9dc-11e9-8eef-f64c9ad8b2a4.png)

Increased linear gradient background design to increase swipe up visibility for the icon as well 
code here: 
```background: linear-gradient(180deg, rgba(0, 0, 0, 0) 50%, #000000 99.85%)```

**Comment by paulchrisluke** [comment]
actually use this instead: https://lottiefiles.com/34-scroll-indicator

**Comment by mort3za** [comment]
There are two questions:  
1. Should we show this animation when the video is playing? (I think it should be visible because the video has autoplay)
2. Should it have an onClick handler? I mean automatically scroll to content after video when user clicks on it.

**Comment by paulchrisluke** [comment]
Yes to both
