### ISSUE TITLE
hero image only (probably) (1h)

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#18]
https://www.figma.com/file/SiFZE7hhRKx2fWmrfZ3uy2RO/Shinta-Mani-Wild?node-id=394%3A3753

Will be a standard hero image for all pages except for the home page.

Home page will need an auto playing video that closely emulates current site behavior.

**Comment by paulchrisluke** [comment]
@mort3za 
I'm looking at adventures, tents, food and drinks, and wellness and i'm not seeing any hero images here? are they connected to the endpoints?

**Comment by mort3za** [comment]
@paulchrisluke adventure link has a typo, I use `adventures` in website but API is `adventure`.
Checked all of the pages, `featuredImage` property is the image that I show on hero section and seems have no problem.

![image](https://user-images.githubusercontent.com/510242/64149786-207e0480-ce3c-11e9-88aa-9abbc18ec3fd.png)

**Comment by paulchrisluke** [comment]
I see, looking good. the top nav still is linked to "adventures" but I see the real page now, looks good!
