### ISSUE TITLE
Gallery Mobile Display

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#183]
The external/internal gallery currently looks like this 
![image](https://user-images.githubusercontent.com/5694308/66477552-95d79780-eac2-11e9-9a44-deb42005afe5.png)

We want the thumbnails of the exterior/interior galleries to be scaled landscape rectangles like the desktop version, like this 
![image](https://user-images.githubusercontent.com/5694308/66477705-e2bb6e00-eac2-11e9-86d4-0dd7227e0d3e.png)

**Comment by mort3za** [comment]
Please remove transformations from images URLs. I'll set them in frontend.  
from:  
https://res.cloudinary.com/ddwsbpkzk/image/upload/c_fill,h_320,w_569/v1567753990/Shinta%20Mani%20Wild/Wild%20Tent/Wild_Tent_Exterior-_Tent_Page_Shinta_Mani_Wild_jzoo9m.jpg  
to:  
https://res.cloudinary.com/ddwsbpkzk/image/upload/v1567753990/Shinta%20Mani%20Wild/Wild%20Tent/Wild_Tent_Exterior-_Tent_Page_Shinta_Mani_Wild_jzoo9m.jpg  

and from:  
url: https://res.cloudinary.com/ddwsbpkzk/image/upload/c_fill,h_320,w_569/v1567753991/Shinta%20Mani%20Wild/Wild%20Tent/Interior_Gallery_-_Wild_Tent_Page_Shinta_Mani_Wild_qkobuz.jpg  
to:  
https://res.cloudinary.com/ddwsbpkzk/image/upload/v1567753991/Shinta%20Mani%20Wild/Wild%20Tent/Interior_Gallery_-_Wild_Tent_Page_Shinta_Mani_Wild_qkobuz.jpg

**Comment by paulchrisluke** [comment]
Transformations are removed in the database now for all gallery thumbnails
