### ISSUE TITLE
Yellow Bar "book now" mobile

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#187]
Right now this is what the mobile "book now" bar looks like
![image](https://user-images.githubusercontent.com/5694308/66699270-71bcc600-ed0f-11e9-947b-666f740afa98.png)
![image](https://user-images.githubusercontent.com/5694308/66699297-c7916e00-ed0f-11e9-814c-5ed5f80e3c47.png)
![image](https://user-images.githubusercontent.com/5694308/66479795-6c6d3a80-eac7-11e9-9697-7b458443226d.png)

Scale the yellow bar so that it is much thinner and smaller (design example is 376x56 pixels in yellow area)
![image](https://user-images.githubusercontent.com/5694308/66480350-b0147400-eac8-11e9-8ea6-c2e9dbe96aa5.png)

Size reference similar to Instagram's bottom nav bar
https://cdn.discordapp.com/attachments/593785406517149697/631464197082972180/image0.png

**Comment by paulchrisluke** [comment]
The bottom yellow bar should be smaller than the top navigation...it is still the same size as before

**Comment by mort3za** [comment]
@smebrahimi If you need to resize button's images, you can change `h_72` to other values in the URL:  
https://res.cloudinary.com/ddwsbpkzk/image/upload/h_72/Shinta%20Mani%20Wild/general/Button_Broken_Right_hyntrd.png  
for example to  
https://res.cloudinary.com/ddwsbpkzk/image/upload/h_48/Shinta%20Mani%20Wild/general/Button_Broken_Right_hyntrd.png

**Comment by mort3za** [comment]
@smebrahimi I have rewritten the button component in PR #215, when it's merged this task is automatically done.
