### ISSUE TITLE
fullwidth image + book button (2h)

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#19]
"adventures await" book now

https://www.figma.com/file/SiFZE7hhRKx2fWmrfZ3uy2RO/Shinta-Mani-Wild?node-id=7%3A26

**Comment by paulchrisluke** [comment]
positioning on the button, do we need to get a different sized frame for you? 

![image](https://user-images.githubusercontent.com/5694308/63485794-f4bf5e00-c4ce-11e9-98a5-19d744cd7f61.png)

**Comment by mort3za** [comment]
@paulchrisluke I assumed that we'll build all of our buttons using that `border-image` property. But for now, I can replace it with another image. Yeah, send it, please.

**Comment by paulchrisluke** [comment]
![Book Now Button Dark](https://user-images.githubusercontent.com/5694308/63510553-0cb3d380-c509-11e9-9051-ddb56f431c08.png)
![Book Now Button Light](https://user-images.githubusercontent.com/5694308/63510556-0d4c6a00-c509-11e9-9650-3154fe3bd0bc.png)

ah smart, yes something I'll add to the backlog (switch buttons to use border-image)

**Comment by paulchrisluke** [comment]
![image](https://user-images.githubusercontent.com/5694308/64089265-73d65100-cd6f-11e9-8478-1b35f674da19.png)
There are some extra space in the side, is it possible for it to maintain full width

**Comment by mort3za** [comment]
@paulchrisluke I can stretch it, but it will look ugly, or we can create another version of that mp4 with 1920px width.  
Most of the cases I saw in these situations, designers make a fade-able image at the left and right edges. for example, we can make a gradient from transparent to black.

**Comment by paulchrisluke** [comment]
We are probably going to remove videos and use static images for mvp 
please also add this gradient to these banners 
background: linear-gradient(270deg, rgba(0, 0, 0, 0) 33.92%, rgba(0, 0, 0, 0.994792) 99.99%, #000000 100%), url(Shinta Mani Wild - Bensley Collection 13.jpg);

**Comment by paulchrisluke** [comment]
Also add shadows to the bottom of banner 
![image](https://user-images.githubusercontent.com/5694308/64588113-a1ed0e00-d3cb-11e9-95da-af765e838ee3.png)

box-shadow: 0px 9px 24px rgba(0, 0, 0, 0.25), 0px 4px 4px rgba(0, 0, 0, 0.25);
