### ISSUE TITLE
Add mute button to hero video players

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#195]
Right now, our header videos autoplay when you enter the page 
![image](https://user-images.githubusercontent.com/5694308/66534366-30c28700-eb40-11e9-9806-bb4533977ab8.png)

there is only play/pause control 
![image](https://user-images.githubusercontent.com/5694308/66534386-3c15b280-eb40-11e9-8514-1d87aa580bd8.png)

Add mute button like the story lightbox mute button in the bottom left 
![image](https://user-images.githubusercontent.com/5694308/66534467-81d27b00-eb40-11e9-8715-f2556b908394.png)

**Comment by mort3za** [comment]
Do we need a volume control? our default volume is 20%, there should be a way to increase volume I think.

related Pen: https://codepen.io/FilipVitas/pen/aXOWYo

**Comment by paulchrisluke** [comment]
It should be responsive to the device's volume control buttons
Facebook is a good example
their mute botton toggles on/off but volume control for their app is dependent on the phone's increase/decrease volume buttons 
For desktop, they do this
![image](https://user-images.githubusercontent.com/5694308/66697077-8f346480-ecfc-11e9-9a90-f53c9dc559ab.png)
![image](https://user-images.githubusercontent.com/5694308/66697081-9d828080-ecfc-11e9-8acd-d9c82fb0237c.png)
![image](https://user-images.githubusercontent.com/5694308/66697084-a70be880-ecfc-11e9-835c-5b0bd6472046.png)
