### ISSUE TITLE
New Quote Card

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#198]
Our current quote card design looks like this 
![image](https://user-images.githubusercontent.com/5694308/66553392-35edf900-eb75-11e9-8c24-48824aa10037.png)
![image](https://user-images.githubusercontent.com/5694308/66553550-882f1a00-eb75-11e9-98a6-ede5ff773747.png)

We have a new quote card design that looks like this one desktop and mobile 
![image](https://user-images.githubusercontent.com/5694308/66553501-6fbeff80-eb75-11e9-9281-8c3d9b9c2c3e.png)
![image](https://user-images.githubusercontent.com/5694308/66553516-777ea400-eb75-11e9-8e7a-65fd206d2433.png)

I've uploaded the card in parts much like the buttons 
The four corners stays in the same corner for both mobile and Desktop
![image](https://user-images.githubusercontent.com/5694308/66553636-b3196e00-eb75-11e9-872b-d5ac7433dc71.png)

Corners: 
1: https://res.cloudinary.com/ddwsbpkzk/image/upload/v1570697476/Shinta%20Mani%20Wild/general/Quote_Box_Corner_1.png
2: https://res.cloudinary.com/ddwsbpkzk/image/upload/v1570697506/Shinta%20Mani%20Wild/general/Quote_Box_Corner_2.png
3: https://res.cloudinary.com/ddwsbpkzk/image/upload/v1570697506/Shinta%20Mani%20Wild/general/Quote_Box_Corner_3.png
4: https://res.cloudinary.com/ddwsbpkzk/image/upload/v1570697506/Shinta%20Mani%20Wild/general/Quote_Box_Corner_4.png

The desktop versions are divided like this, and uses the Desktop body 
![image](https://user-images.githubusercontent.com/5694308/66553252-f9220200-eb74-11e9-83ac-7d0d2839eb42.png)

Desktop: 
https://res.cloudinary.com/ddwsbpkzk/image/upload/v1570697505/Shinta%20Mani%20Wild/general/Desktop_Quote_Box_Body.png

The mobile versions are divided like this and uses the mobile body 
![image](https://user-images.githubusercontent.com/5694308/66553314-1060ef80-eb75-11e9-81be-006f8ff236c8.png)

Mobile: https://res.cloudinary.com/ddwsbpkzk/image/upload/v1570697506/Shinta%20Mani%20Wild/general/MOBILE_Quote_Box_body.png

**Comment by paulchrisluke** [comment]
![image](https://user-images.githubusercontent.com/5694308/66695805-ccdec080-ecef-11e9-8cbe-96e9ae6d8c61.png)
New quote card reuploaded. Pieces 1-8, numbered from upper left hand corner, clockwise
1: https://res.cloudinary.com/ddwsbpkzk/image/upload/v1570859485/Shinta%20Mani%20Wild/general/Quote_Box_1.png
2: https://res.cloudinary.com/ddwsbpkzk/image/upload/v1570859486/Shinta%20Mani%20Wild/general/Quote_Box_2.png
3: https://res.cloudinary.com/ddwsbpkzk/image/upload/v1570859485/Shinta%20Mani%20Wild/general/Quote_Box_3.png
4: https://res.cloudinary.com/ddwsbpkzk/image/upload/v1570859486/Shinta%20Mani%20Wild/general/Quote_Box_4.png
5: https://res.cloudinary.com/ddwsbpkzk/image/upload/v1570859485/Shinta%20Mani%20Wild/general/Quote_Box_5.png
6: https://res.cloudinary.com/ddwsbpkzk/image/upload/v1570859485/Shinta%20Mani%20Wild/general/Quote_Box_6.png
7: https://res.cloudinary.com/ddwsbpkzk/image/upload/v1570859485/Shinta%20Mani%20Wild/general/Quote_Box_7.png
8: https://res.cloudinary.com/ddwsbpkzk/image/upload/v1570859486/Shinta%20Mani%20Wild/general/Quote_Box_8.png

**Comment by paulchrisluke** [comment]
Spacing, sizing, etc is good 

![image](https://user-images.githubusercontent.com/5694308/66710804-92395e80-eda9-11e9-94ca-7f3166224ec4.png)
![image](https://user-images.githubusercontent.com/5694308/66710763-ff98bf80-eda8-11e9-95a1-e12275564b99.png)

There's a little bit of an overlap issue with the quote box and the text inside on the top right and bottom left corner, seeing this on all quote cards 

We want the text to not be hidden by any of the card pieces

**Comment by paulchrisluke** [comment]
![image](https://user-images.githubusercontent.com/5694308/66712147-9e7de580-edc2-11e9-8d3b-dab440107904.png)
It seems like over here there is a spacing issue. Make sure the card is filled with the card color

Also, homepage is still on the old quote card 
![image](https://user-images.githubusercontent.com/5694308/66712157-bbb2b400-edc2-11e9-8e4a-dc999218326e.png)

**Comment by mort3za** [comment]
Sorry, the background-color gap filled.

> Also, homepage is still on the old quote card on desktop and responsive desktop chrome

I had the same view, it was cache. ctrl+f5 renewed it.
