### ISSUE TITLE
Stories: 4 image + underlay text + favorite icon (2h)

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#20]
That like <3 button needs to send like data back to postgres. We will send what the user likes to management on booking. Later, we are going to use like's to organize the site content (if a user likes food stuff, show food images).

If that is too complicated to do on first pass, we can icebox the data transfer stuff and simply allow it to be colored. 

When clicking on the actual sqaures, we will open the "story mode" template, showing a story about each activity. I'll find the related issue for the story template and attach it here in a sec.

**Comment by mort3za** [comment]
Chris: 
these open up new pages, like this https://stagingapi.whynot.earth/api/v0/pages/slug/shintamaniwild/shinta-mani-foundation
but in the same story/lightbox gallery format

**Comment by mort3za** [comment]
Crhis:
https://mashable.com/2018/02/13/reels-guide-to-black-panther.amp
thats our "lightbox gallery"

**Comment by paulchrisluke** [comment]
yes

**Comment by paulchrisluke** [comment]
![image](https://user-images.githubusercontent.com/5694308/64500622-28c8ba80-d2e8-11e9-9eb0-751cd38ace81.png)
At the moment, these story thumbnails are shown within the staging as multiple duplicates because within the database, there are multiple entries for each singular story thumbnails. 
![image](https://user-images.githubusercontent.com/5694308/64500702-76452780-d2e8-11e9-9106-f531b1aec386.png)
The multiple entries are for the different ordered cards that are to show up in the lightbox when a visitor clicks on a thumbnail for a specific topic, for example, "foot massage". So, each thumbnail has an order of 1 to up to 7 to show what order the story are presented within the lightbox
![image](https://user-images.githubusercontent.com/5694308/64500763-b7d5d280-d2e8-11e9-81ef-28a67694dada.png)

What we want is for the collection of thumbnails to only show order number 1 of each story on a page. 
![image](https://user-images.githubusercontent.com/5694308/64500812-f79cba00-d2e8-11e9-8692-6797e38f5276.png)

So, for the wellness page for example, there should only be 5 story thumbnails
![image](https://user-images.githubusercontent.com/5694308/64500851-2fa3fd00-d2e9-11e9-818e-086b134cd383.png)

As each of the stories are mp4s, we also want a video preview that plays on hover just like how Youtube presents its video thumbnails.

**Comment by mort3za** [comment]
Okay no problem, but I don't see the `order` property on stories in the API response.  
Btw, what is the `blur` prop on stories?

**Comment by paulchrisluke** [comment]
@StrangeWill we are not seeing teh order property in the api response for cards/stories, bug?

https://stagingapi.whynot.earth/api/v0/pages/slug/shintamaniwild/Wild-tents

@mort3za blur is not needed right now, we can ignore.

**Comment by paulchrisluke** [comment]
The stories were originally in the posterURL section 
https://user-images.githubusercontent.com/5694308/64500702-76452780-d2e8-11e9-9106-f531b1aec386.png

But these story videos have now been moved into the BackgroundURL section for each entry. Story URL's now contain placeholder images for each card

**Comment by paulchrisluke** [comment]
Going to close this and separate out issues. Will tag.
