### ISSUE TITLE
Remove "View Tents" button

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#228]
**Is your feature request related to a problem? Please describe.**
Remove the "View Tents" button from the top nav bar and mobile navigation. Clients think it is redundant and the tents area works just fine. 
![image](https://user-images.githubusercontent.com/5694308/66904125-c7ee7980-f02d-11e9-940b-1495865d1114.png)
![image](https://user-images.githubusercontent.com/5694308/66904564-7c889b00-f02e-11e9-8778-e66a98e786b9.png)

**Describe the solution you'd like**
Remove the button from the top navigation and the mobile navigation and readjust text options according to the design 

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://user-images.githubusercontent.com/5694308/66904510-67ac0780-f02e-11e9-90ec-e268c5462337.png)
![image](https://user-images.githubusercontent.com/5694308/66904529-72669c80-f02e-11e9-8ae3-0107d18c0db7.png)

**Comment by mort3za** [comment]
#96

**Comment by mort3za** [comment]
I love the ideas of this client, they are so wise.
