### ISSUE TITLE
left image card (1h)

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#23]
https://www.figma.com/file/SiFZE7hhRKx2fWmrfZ3uy2RO/Shinta-Mani-Wild?node-id=241%3A90

**Comment by paulchrisluke** [comment]
I think we need a png frame that does not have the gradient around and add it with css instead. I'll get that from Nikita.

**Comment by mort3za** [comment]
@paulchrisluke In this case, we should always create that image when we want to replace it with another image. But on my side, I think it's a better way because of different browser rendering in these 3D CSS effects.

**Comment by paulchrisluke** [comment]
![Book Now Button Dark](https://user-images.githubusercontent.com/5694308/63510475-dece8f00-c508-11e9-8a81-4ffc57fa5d2c.png)
![Book Now Button Light](https://user-images.githubusercontent.com/5694308/63510476-df672580-c508-11e9-8a41-d171be13f6bf.png)
 try these instead. Should we use cloudinary for these too?

**Comment by mort3za** [comment]
@paulchrisluke It's our CDN, every asset should be on cloudinary.
