### ISSUE TITLE
font-family of cards in tents page is wrong

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#230]
The title of each font card currently in each page should be:
![image](https://user-images.githubusercontent.com/5694308/66906845-89a78900-f032-11e9-939f-24ff0ccf0e8c.png)

However, in the tent page (https://elegant-perlman-ff2d63.netlify.com/tents), the title of the font cards are still the Shinta Mani Font:
![image](https://user-images.githubusercontent.com/5694308/66906903-a5ab2a80-f032-11e9-853e-7d7b63c3fd16.png)

Change the title fonts of these cards AND of the amenities titles into the same as the other pages. Conservation card code from home page as example.
```
<h2 data-v-5790c166="" data-v-1bce2f4c="" class="base-heading text-small-caps font-sans-serif font-weight-normal h2 mb-3 text-dark text-center text-xl-left">Conservation</h2>
```

**Comment by paulchrisluke** [comment]
![image](https://user-images.githubusercontent.com/5694308/66972989-b1453280-f0c0-11e9-9c7f-137538ea1c30.png)
Also change this section title to the right font please

**Comment by mort3za** [comment]
Will do it in issue 229
