### ISSUE TITLE
Change Video Quality settings

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#237]
Current video settings for our hero video are set at ```q_auto```, and the resolution of our videos can get a little low
![image](https://user-images.githubusercontent.com/5694308/66974508-7bef1380-f0c5-11e9-9ba1-30962c5e0082.png)

Change video quality to ```q_auto: best``` so the resolution is not as bad.

**Comment by SimonRask** [comment]
@paulchrisluke 
Should it be changed for all videos?

**Comment by paulchrisluke** [comment]
Yep!
