### ISSUE TITLE
book now buttons (dark, light) (1h)

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#24]
https://www.figma.com/file/SiFZE7hhRKx2fWmrfZ3uy2RO/Shinta-Mani-Wild?node-id=241%3A90

**Comment by mort3za** [comment]
https://res.cloudinary.com/ddwsbpkzk/image/upload/v1568541216/Shinta%20Mani%20Wild/general/book-now-lite_ma33ou.png

https://res.cloudinary.com/ddwsbpkzk/image/upload/v1568541216/Shinta%20Mani%20Wild/general/book-now-colorful_vfgh3k.png
