### ISSUE TITLE
animate the divider line

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#244]
animate new divider line in ae to use as a pilot for lottie animation integrations

**Comment by skyabode** [comment]
Initial version for testing is here:

https://lottiefiles.com/share/Ej2j2G

**Comment by paulchrisluke** [comment]
@mort3za @atharva3010 we want to start testing lotti animations, replacing our divider line here with this new lottie animation. How hard is that?

![image](https://user-images.githubusercontent.com/5694308/67137832-7fb99c00-f265-11e9-915f-7bd87ba38400.png)

**Comment by mort3za** [comment]
Should be easy I think.

--
Morteza Ziyae
Frontend Engineer

**Comment by skyabode** [comment]
Here is demo with html and js ... ;)

[Archive.zip](https://github.com/whynotearth/shinta-mani-wild/files/3746423/Archive.zip)

**Comment by paulchrisluke** [comment]
@SimonRask you may be interested in this one. It's basically building a vue component which will allow loading of lottie json animation files. Would be handy to use in a variety of cases...

**Comment by skyabode** [comment]
Yes, there are different ways animation can be displayed, for example a simple animation that play from beginning to end,  but also can be a button where playhead needs to be adjusted depending on button states ... I am already working  with some code for these - happy to share!

**Comment by SimonRask** [comment]
@skyabode That's cool. Have you been working on this in this codebase, or somewhere else?

**Comment by skyabode** [comment]
Search and Compile! Doing a lot of research now  just to be able to test the interactions locally - but since I am not a JS expert, I could definitely use some help, lol ...

**Comment by paulchrisluke** [comment]
@SimonRask @mort3za , you two are welcome to work on this. I've assigned @skyabode other work. We need a component that is flexible enough to allow us to deploy a variety of lottie animations through the site from loading icons, to animated backgrounds, to hero image areas, etc.

**Comment by SimonRask** [comment]
@paulchrisluke Okay. I might start working on it today

**Comment by paulchrisluke** [comment]
@SimonRask this would be a good one. Make a component which allows us to display lottie animations.

**Comment by skyabode** [comment]
Hey - how is it going in Cabmodia? Tom :)
