### ISSUE TITLE
responsive menu + toggle (3h)

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#25]
https://www.figma.com/file/SiFZE7hhRKx2fWmrfZ3uy2RO/Shinta-Mani-Wild?node-id=241%3A90
Our mobile menu looks like this 
![image](https://user-images.githubusercontent.com/5694308/66253429-796def00-e792-11e9-92c9-fc43133b1c50.png)
The green Shinta Mani text is not clickable, only the black text is.
At the bottom there's a button linking to tents page just like the current desktop header nav.
They should all be linked to the same links as the desktop nav 

The menu dropping down on click of shinta mani logo is the design, but if the default mobile menu is easier that is ok too for the sake of deadline

**Comment by mort3za** [comment]
@smebrahimi

**Comment by paulchrisluke** [comment]
New mobile menu design including hamburger menu item
![image](https://user-images.githubusercontent.com/5694308/66267228-9e2c9a00-e858-11e9-9e4e-6c6e88ba5d42.png)

can copy style of the default library

SVG of hamburger menu item attached: 
https://res.cloudinary.com/ddwsbpkzk/image/upload/v1570355029/Shinta%20Mani%20Wild/general/menu_24px_e3zpqv.svg
