### ISSUE TITLE
Smoother Swipe Transition 

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#255]
**Is your feature request related to a problem? Please describe.**
Our current lightbox story/gallery swipe motion is very choppy. It is slow to swipe and gets stuck halfway before continuing its movement later on (see gif)

**Describe the solution you'd like**
We want a smooth transition when swiping left or right that isn't as choppy. Good example would be movement of facebook or instagram stories and how the swipe just goes with the movement of your fingers. 

**Additional context**
https://res.cloudinary.com/ddwsbpkzk/video/upload/v1571479618/Shinta%20Mani%20Wild/Bugs/video-1571478944_vhhhxy.mp4

**Comment by paulchrisluke** [comment]
I noticed last night that the swipe is definitely much smoother but the tap motions are gone...we still want the tap motions but does that interfere with the swipe transitions? 
![image](https://user-images.githubusercontent.com/5694308/67629657-7060d100-f8ab-11e9-8bba-d84600acd3c6.png)

**Comment by mort3za** [comment]
@paulchrisluke yes the standard tap areas of swiper can't be there, but let me try to build custom tap areas, probably can solve it.
