### ISSUE TITLE
Adjust Gallery Title Sizing in Mobile

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#262]
We changed fonts from Shinta Mani to Modern King and now sizing is a little different for the fonts 
![image](https://user-images.githubusercontent.com/5694308/67192278-7ecb6a80-f41d-11e9-8c58-fbaccf8acf44.png)
![image](https://user-images.githubusercontent.com/5694308/67192816-732c7380-f41e-11e9-9637-85554d3e927c.png)

Adjust the font sizing for mobile so that the gallery titles fit within the boxes and does not jut out 
Seems like it is in H1 text according to code
![image](https://user-images.githubusercontent.com/5694308/67192700-3e202100-f41e-11e9-970d-6eec41bcfab2.png)

![image](https://user-images.githubusercontent.com/5694308/67192718-45dfc580-f41e-11e9-91ec-373542238703.png)
Follow figma design, which uses H2 text for these gallery boxes. H2 Text is the same for all categories and headers.

**Comment by mort3za** [comment]
This issue has fixed in #263
