### ISSUE TITLE
yellow book now bar (1.5h)

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#27]
https://www.figma.com/file/SiFZE7hhRKx2fWmrfZ3uy2RO/Shinta-Mani-Wild?node-id=241%3A90

**Comment by paulchrisluke** [comment]
yellow bar should be fixed to the bottom of the page as user are scrolling, feature not reflected in figma sheet

**Comment by paulchrisluke** [comment]
moved back because changes not made, see https://github.com/whynotearth/shinta-mani-wild/issues/27#issuecomment-526988277

**Comment by mort3za** [comment]
OK, it's fixed to screen, then what happens when it reaches the end of our page? In Airbnb example, booking bar goes under the footer but we have a small margin below booking bar, so when user scrolls to the bottom of our page, booking bar should go above the footer, right?

**Comment by paulchrisluke** [comment]
yes this is right @mort3za
