### ISSUE TITLE
responsive slider (3h)

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#28]
What is responsive slider in reference to?

On the /tents page, we want to link to other pages /wild-tents/ /waterfall-tents/ and /wildlife-alliance tents. These are the 3 different room types we have at shinta mani wild.
![image](https://user-images.githubusercontent.com/5694308/66252826-593a3200-e78a-11e9-8283-80d4a1ebf7ed.png)

Before interaction, we want these cards to look something like this, where the last option is visible but a little obsured (maybe let it peek out a little more than this
![image](https://user-images.githubusercontent.com/5694308/66252995-52acba00-e78c-11e9-9e33-3efaa5a2e79f.png)

The movement of this slider will be much like that of netflix's sliders
![image](https://user-images.githubusercontent.com/5694308/66252941-77546200-e78b-11e9-91c0-00850a695e61.png)

![image](https://user-images.githubusercontent.com/5694308/66252951-98b54e00-e78b-11e9-8360-cd5c4dc0c76c.png)

Where you can move to the next item

**Comment by mort3za** [comment]
> The movement of this slider will be much like that of netflix's sliders

Can't find the slider, link, please.
Probably you mean something like this? https://swiperjs.com/demos/150-freemode.html

@paulchrisluke

**Comment by mort3za** [comment]
We have already included swiper.js in our project. https://swiperjs.com/  
Every other slider should use it.

**Comment by paulchrisluke** [comment]
yea swiperjs is fine, was just using netflix as an example

**Comment by paulchrisluke** [comment]
![image](https://user-images.githubusercontent.com/5694308/66330172-10d16e80-e95a-11e9-9680-7d44a4c9e11a.png)
These images should also be the same style as the other pages 

![image](https://user-images.githubusercontent.com/5694308/66330215-22b31180-e95a-11e9-8f56-fa0a6129d716.png)

**Comment by SimonRask** [comment]
Has anyone started working on this?

**Comment by paulchrisluke** [comment]
If it is in todo then the latest comment is not currently being worked on.
If you start working on it, self assign and move to in progress

**Comment by SimonRask** [comment]
Okay will keep in mind :)

**Comment by SimonRask** [comment]
@paulchrisluke Do you want navigation and index indicators like the ones on netflix?

This is the current look:
![billede](https://user-images.githubusercontent.com/33556894/67306231-eacdd180-f4f6-11e9-9c19-b5dcfd990af1.png)

Mobile:
![billede](https://user-images.githubusercontent.com/33556894/67306330-13ee6200-f4f7-11e9-8222-353972a10677.png)

**Comment by mort3za** [comment]
I think this should only be active on mobile, because it's already good on
desktop without slider.

**Comment by SimonRask** [comment]
I don't know what I think looks best. Just followed the design

> Before interaction, we want these cards to look something like this, where the last option is visible but a little obsured (maybe let it peek out a little more than this
> ![image](https://user-images.githubusercontent.com/5694308/66252995-52acba00-e78c-11e9-9e33-3efaa5a2e79f.png)

**Comment by mort3za** [comment]
*hmmm*, OK you create the PR. Thank you.

@bamboochow but we need to change design, the only way to see next slide in desktop is dragging. This isn't a good UX.

**Comment by paulchrisluke** [comment]
First of all, great work @SimonRask , you are the 4th contributor to really get in and start making real changes in production, congrats!

Second, I am ok with the UX of dragging in this case and it is purposeful. The two bedroom tent is a single accomodation, a very low priority booking... we want people to know its available, but are ok with people doing a bit of work to see it... its mostly built for families and such, people who are willing to do more work to find accomodation. Our main CTA and buttons we want to drag people to are the Wild and Waterfall tents.
