### ISSUE TITLE
Featured Story Text Cutoff

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#281]
**Describe the bug**
We had this bug before but with the shinta mani font, now need to adjust for modern king font. Longer featured post names are cut off and not visible. This is an earlier client complaint as well. 

**To Reproduce**
1. Go to https://shintamaniwild.com/search/adventure or https://shintamaniwild.com/search/foundation on mobile browser
2. Scroll down to featured posts 
3. See error

**Expected behavior**
Make entire text visible. We need text sizing that fits exactly within the sizing of the story cards without any cutoff or extra text hanging off the side when there's a longer word in a title, with a character limit of 13 per line

**Screenshots**
![image](https://user-images.githubusercontent.com/5694308/67629954-82de0900-f8b1-11e9-8ae5-9249e853c15b.png)
https://cdn.discordapp.com/attachments/593785406517149697/637785009566121995/image0.png

**Smartphone (please complete the following information):**
 - Device: iphone 8, browser inspect iphone x 
 - OS: 
 - Browser chrome
 - Version

**Comment by mort3za** [comment]
Our text, font-size and dedicated space for title don't match. We should choose between these two:  
![localhost_8080_search_adventure(iPhone 6_7_8)](https://user-images.githubusercontent.com/510242/67658536-1590ad80-f96f-11e9-8f9a-192666d78d23.png)

![localhost_8080_search_adventure(iPhone 6_7_8) (1)](https://user-images.githubusercontent.com/510242/67658632-643e4780-f96f-11e9-9eb0-e463cb8e75e8.png)


The second option is not reliable if we have even longer text.
