### ISSUE TITLE
Make components shareable

### ISSUE THREAD

**Issue by mort3za** [whynotearth/shinta-mani-wild#303]
I found two ways of doing it. git submodules and Bit.  
But our main concern should be a good design and following the SOLID principle.

**Comment by mort3za** [comment]
Currently, I'm testing [Bit](https://bit.dev/).

**Comment by paulchrisluke** [comment]
we went with tailwind on other projects, looking to making it a packaged thing or something. Closing this issue on this project for now since it is canceleld
