### ISSUE TITLE
Put placeholders where content is supposed to load

### ISSUE THREAD

**Issue by atharva3010** [whynotearth/shinta-mani-wild#34]
Right now we can set a min-height in place of a placeholder so that the user expects that there is incoming content till api loads, like how we do on vkirirom site  
  
Before api load:  
![image](https://user-images.githubusercontent.com/34229217/63651495-e85b2f80-c772-11e9-93b5-8d989a6a9c0d.png)  
  
After api load:  
![image](https://user-images.githubusercontent.com/34229217/63651509-0a54b200-c773-11e9-90a4-91add7fb3d6e.png)  
  
Similarly, we need to do for shinta mani wild.  
  
Current issue (no blank space placeholder), so
before api load:  
![image](https://user-images.githubusercontent.com/34229217/63651542-56075b80-c773-11e9-8446-edbdafed8360.png)
  
after api load:  
![image](https://user-images.githubusercontent.com/34229217/63651549-6586a480-c773-11e9-8b83-ff025a7b4eba.png)
  
This shows content pushing down, once content loads, it is a bad user experience practice and also my and @paulchrisluke 's pet peeve. I think there should be a minimum height blank space to indicate incoming content.

**Comment by paulchrisluke** [comment]
It is one of my pet peeves haha. This is a good article on the subject with ideas: https://www.codepicky.com/content-placeholders/

**Comment by paulchrisluke** [comment]
Current loading placeholders are like this: 
![image](https://user-images.githubusercontent.com/5694308/64604025-94e01700-d3eb-11e9-9d78-ef0c56510fbf.png)

Compared to the actual content: 
![image](https://user-images.githubusercontent.com/5694308/64604061-aaedd780-d3eb-11e9-9139-101279c512ed.png)

We are trying to prevent the action of content being pushed down visually when its fully loaded. Placeholders must have the same sizes/spaces as the actual content.

**Comment by mort3za** [comment]
Hmmm, I understand.  
Maybe changing the font-size of h1 caused this.  
Anyway, for the top section of the pages, it's easy to handle it, but for bottom sections we don't know the exact height of the content (i.e. description text is longer) so I can't predict it 100% correct.

**Comment by paulchrisluke** [comment]
I can limit characters to make sure we are always 2 line, 3 line etc. Will
that help?

**Comment by mort3za** [comment]
Yes!

**Comment by paulchrisluke** [comment]
Character limit: 95 for all card sizes, so the smaller cards would be about 3 lines, the longer ones would fit about 2 lines of text (same content)

**Comment by mort3za** [comment]
[Pending for https://github.com/whynotearth/meredith-core/issues/50]
