### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#36]
Current staging contact page looks exactly like all other pages 
![image](https://user-images.githubusercontent.com/5694308/64502753-12276100-d2f2-11e9-8c18-29c602d2410a.png)

Contact page has is own unique page setup different from the others 
![image](https://user-images.githubusercontent.com/5694308/64502776-32572000-d2f2-11e9-84b1-173ca7dfa4f8.png)
https://www.figma.com/file/SiFZE7hhRKx2fWmrfZ3uy2RO/Shinta-Mani-Wild?node-id=0%3A1

Create Contact Page and connect page to footer link #26

**Comment by mort3za** [comment]
Atharva:
remaining parts are  
- 'How to get here' link
- icons
- that image button

**Comment by paulchrisluke** [comment]
![image](https://user-images.githubusercontent.com/5694308/64954585-48478080-d8b0-11e9-8b93-40eb7d2a42e5.png)
Current contact sheet based on deployment preview link
Design of contact sheet has been updated in figma to include a page description and correct copy placement
![image](https://user-images.githubusercontent.com/5694308/64954758-bd1aba80-d8b0-11e9-806b-f0ce1ad1025c.png)
Page description has been added to database
![image](https://user-images.githubusercontent.com/5694308/64954931-1f73bb00-d8b1-11e9-87b6-9025658b6b7e.png)

Icon also needs to be added to text fields: 
![image](https://user-images.githubusercontent.com/5694308/64954966-39150280-d8b1-11e9-8141-8fe4c1727aeb.png)

Copy included below: 
The journey to Wild takes approximately 2 hours by road from Sihanoukville (KOS) Airport and 3 hours from Phnom Penh (PNH) Airport, and we can arrange pick up from both city centre vicinity if you are coming from coastal Cambodia and continuing to the capital.  There are daily flights connecting the cultural heart of Siem Reap (REP) to both airports, and the flight time is approximately 50 mins.

Direct flight from Bangkok (DMK/BKK) to Sihanoukville (KOS) was launched this year with AirAsia and JC Airlines on selected day of week.  Starting from 1st January 2020 Bangkok Airways will be flying daily between the two cities.

Wild is accessible by private helicopter from Phnom Penh, Sihanoukville and Siem Reap, information and cost available upon request.
