### ISSUE TITLE
"story mode" lightbox which opens when cards are clicked

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#37]
looks like this, essentially:
https://mashable.com/2018/02/13/reels-guide-to-black-panther.amp

![image](https://user-images.githubusercontent.com/5694308/64474114-0d4f9980-d19a-11e9-9119-c3f83ab52ef8.png)

design in wellness page: https://www.figma.com/file/SiFZE7hhRKx2fWmrfZ3uy2RO/Shinta-Mani-Wild?node-id=394%3A3756

**Comment by mort3za** [comment]
In #21 you said this is a standalone page and here is a lightbox, Is this a duplicate issue or is something different?

**Comment by paulchrisluke** [comment]
standalone page (just looks like lightbox I guess)
