### ISSUE TITLE
create "onesie towsies" list of action items we need to create to "finish" the site

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#39]
PWA icons and sizes, favcon items, logos, what are we missing? We are going to build this info into the cms, so having it outlined for this and all future projects will help ease future onboarding.

**Comment by atharva3010** [comment]
We need icons in these sizes for PWAs:  
![image](https://user-images.githubusercontent.com/34229217/64492521-30f60b00-d292-11e9-93e9-5c225d6e3a4e.png)  
White background for apple icons and transparent backgrounds for all others.  
We need a favicon in the size of 32x32

**Comment by paulchrisluke** [comment]
what size does apple-touch-icon.png , logo.png, and safaripinned-tab.svg need to be?

the rest are here:

https://res.cloudinary.com/ddwsbpkzk/image/upload/c_scale,w_192/v1567999152/Shinta%20Mani%20Wild/Bensley_Collection_Shinta_ManiWild_brandmark_white_plz7zt.png
https://res.cloudinary.com/ddwsbpkzk/image/upload/c_scale,w_512/v1567999152/Shinta%20Mani%20Wild/Bensley_Collection_Shinta_ManiWild_brandmark_white_plz7zt.png
https://res.cloudinary.com/ddwsbpkzk/image/upload/c_scale,w_60/v1567999151/Shinta%20Mani%20Wild/Bensley_Collection_Shinta_ManiWild_brandmark_Black_u5cdbh.png
https://res.cloudinary.com/ddwsbpkzk/image/upload/c_scale,w_76/v1567999151/Shinta%20Mani%20Wild/Bensley_Collection_Shinta_ManiWild_brandmark_Black_u5cdbh.png
https://res.cloudinary.com/ddwsbpkzk/image/upload/c_scale,w_120/v1567999151/Shinta%20Mani%20Wild/Bensley_Collection_Shinta_ManiWild_brandmark_Black_u5cdbh.png
https://res.cloudinary.com/ddwsbpkzk/image/upload/c_scale,w_152/v1567999151/Shinta%20Mani%20Wild/Bensley_Collection_Shinta_ManiWild_brandmark_Black_u5cdbh.png
https://res.cloudinary.com/ddwsbpkzk/image/upload/c_scale,w_180/v1567999151/Shinta%20Mani%20Wild/Bensley_Collection_Shinta_ManiWild_brandmark_Black_u5cdbh.png
https://res.cloudinary.com/ddwsbpkzk/image/upload/c_scale,w_32/v1567999152/Shinta%20Mani%20Wild/Bensley_Collection_Shinta_ManiWild_brandmark_white_plz7zt.ico
https://res.cloudinary.com/ddwsbpkzk/image/upload/c_scale,w_16/v1567999152/Shinta%20Mani%20Wild/Bensley_Collection_Shinta_ManiWild_brandmark_white_plz7zt.png
https://res.cloudinary.com/ddwsbpkzk/image/upload/c_scale,w_32/v1567999152/Shinta%20Mani%20Wild/Bensley_Collection_Shinta_ManiWild_brandmark_white_plz7zt.png
https://res.cloudinary.com/ddwsbpkzk/image/upload/c_scale,w_144/v1567999152/Shinta%20Mani%20Wild/Bensley_Collection_Shinta_ManiWild_brandmark_white_plz7zt.png
https://res.cloudinary.com/ddwsbpkzk/image/upload/c_scale,w_150/v1567999152/Shinta%20Mani%20Wild/Bensley_Collection_Shinta_ManiWild_brandmark_white_plz7zt.png

**Comment by paulchrisluke** [comment]
@atharva3010 what size does apple-touch-icon.png , logo.png, and safaripinned-tab.svg need to be?
