### ISSUE TITLE
Home Page not linked to API

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#40]
Current home page shows placeholder images 
![image](https://user-images.githubusercontent.com/5694308/64501649-69c2ce00-d2ec-11e9-84c4-38e8c6256e80.png)

Images have already been loaded to database 
![image](https://user-images.githubusercontent.com/5694308/64501659-76472680-d2ec-11e9-961a-a548a46e5d68.png)

Connect home page to API so that images will replace placeholders within our staging

**Comment by mort3za** [comment]
The only part that is not connected yet is the cards texts.
