### ISSUE TITLE
Tents Page Sub-nav for Waterfall, Wild, Wildlife Alliance Tents 

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#44]
At the moment within the staging, tents page has the same gallery as waterfall and wild tents with internal and external 
![image](https://user-images.githubusercontent.com/5694308/64502413-3aae5b80-d2f0-11e9-836e-909108236933.png)

Images have been inputed in cloudinary and database in the order of wild, waterfall, wildlife alliance 

Tents page needs subnav for 3 tent types in the style of thumbnail cards so visitors can click to nav to the 3 tent pages 
![image](https://user-images.githubusercontent.com/5694308/64502457-6893a000-d2f0-11e9-9d7a-a1837bcda49c.png)

In addition, we need to design a subnav drop down for the 3 options so visitors can nav directly from the top-nav to the 3 tent style pages
![image](https://user-images.githubusercontent.com/5694308/64502958-228c0b80-d2f3-11e9-994c-227ba2d35187.png)

Top nav design has been edited to reflect drop down 
![image](https://user-images.githubusercontent.com/5694308/64503229-3f750e80-d2f4-11e9-91b2-3917ded4d989.png)

Make drop down subnav using this, with the same font/color scheme as our current top nav
https://bootstrap-vue.js.org/docs/components/dropdown/
![image](https://user-images.githubusercontent.com/5694308/64503267-65021800-d2f4-11e9-989d-b29fcaf1050c.png)

**Comment by mort3za** [comment]
Please fix me if I'm wrong:  
1. add a dropdown in the header with links to three tents
2. `Tents` page should have 3 `featured story` but with links to three tents pages (waterfall, ...)

A question, we are converting `Tents` link in the header to a dropdown and it will have only 3 subnav, then how users can go to `Tents` page?

**Comment by mort3za** [comment]
> add a dropdown in the header with links to three tents
Tents page should have 3 featured story but with links to three tents pages (waterfall, ...)
For this section, I should only convert the link of tents page from `/listing/tents` to `/search/tents` and you can set the first 3 stories to what you want. (I'll add a condition to show 3 featured stories instead 2 in this page)

**Comment by paulchrisluke** [comment]
Book now buttons link to /tents/ as we need the user to hit that page first
before choosing. Also can we make the tents link in the nav still link
there ?

**Comment by mort3za** [comment]
OK  
> Also can we make the tents link in the nav still link
there ?
We can but the area of tapping to open dropdown will be so small and it's not intended to open a page by clicking a dropdown.

**Comment by paulchrisluke** [comment]
![image](https://user-images.githubusercontent.com/5694308/65210688-30494a00-dac6-11e9-8681-5c93e11cf2b0.png)
Current Nav includes a white background with black text 

We want the dropdown nav to match the colors of the top nav 
![image](https://user-images.githubusercontent.com/5694308/65210761-67b7f680-dac6-11e9-9023-a68cbd076150.png)

On hover, invert the colors: White background, olive text 
![image](https://user-images.githubusercontent.com/5694308/65210856-d432f580-dac6-11e9-96a7-a61418da8ba4.png)

Samples are not 8x8, only for color purposes
