### ISSUE TITLE
add hero video player

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#60]
within the api, we've added a new series of videos for `order:5` these 15 second clips make up the total hero video area. We split them up in 15 seconds to make quicker page load. Video player should auto play (start muted), have a slider indicator, and roughly match a landscape version of
https://mashable.com/2018/02/13/reels-guide-to-black-panther.amp

https://stagingapi.whynot.earth/api/v0/pages/slug/shintamaniwild/home

**Comment by mort3za** [comment]
If we split a single video into multiple parts, then autoplay them, it won't help page load performance.  
I think the point of the slider in the Mashable link is the story concept (like Instagram) and *different* videos.  
Do you think like me?

**Comment by paulchrisluke** [comment]
We're not doing the story view anymore, we're going to have it be exactly the same as the https://www.bensleycollection.com/shintamani-wild/ heading auto video player
