### ISSUE TITLE
"No Items To Show" In Tent Page

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#63]
Tent Page Cards for Waterfall, Wild, Wildlife Alliance Tent are now showing "No Items To Show" instead of cards
![image](https://user-images.githubusercontent.com/5694308/64834233-4315d780-d60b-11e9-8627-53be3877f03f.png)
![image](https://user-images.githubusercontent.com/5694308/64834253-52952080-d60b-11e9-9c86-2cafec48bd46.png)

Should be showing waterfall, wild, wildlife alliance cards on the top
![image](https://user-images.githubusercontent.com/5694308/64834270-7193b280-d60b-11e9-9905-add103232f96.png) 

The bottom should have the all inclusive/personal butler cards much like the home page, plus text for Ameneties 

![image](https://user-images.githubusercontent.com/5694308/64834313-a56ed800-d60b-11e9-8127-838347331b5e.png)

![image](https://user-images.githubusercontent.com/5694308/64834323-adc71300-d60b-11e9-92b6-87161196218c.png)

**Comment by mort3za** [comment]
> The bottom should have the all inclusive/personal butler cards much like the home page, plus text for Ameneties
#22

**Comment by mort3za** [comment]
> Tent Page Cards for Waterfall, Wild, Wildlife Alliance Tent are now showing "No Items To Show" instead of cards
> Should be showing waterfall, wild, wildlife alliance cards on the top
Is this `/search/tents` page? I can't find related data in API

**Comment by mort3za** [comment]
This request returns an empty array:  
https://stagingapi.whynot.earth/api/v0/pages/slug/shintamaniwild/categories/by-name/tents

Let me know if I should get data from another path @StrangeWill

**Comment by paulchrisluke** [comment]
https://stagingapi.whynot.earth/api/v0/pages/slug/shintamaniwild/categories/by-name/accommodations

**Comment by mort3za** [comment]
> Shinta Mani Wild is a radical new fusion of world-class design, hospitality and conservation. The camp was born when world-renowned designer Bill Bensley identified an unprotected, 350-hectare wildlife corridor – and set out to save it from poaching, mining and logging. Sustainability informs everything we do, hence our partnership with the Wildlife Alliance (whose rangers have an onsite station), and our resident naturalists, who assist our chef. The Shinta Mani Fo on wildlife expeditions, foraging tours and more.


This is the text of card in tents page in Figma.  
seems this part is not correct: **The Shinta Mani Fo on wildlife expeditions, foraging tours and more.**
please send me the correct text.

**Comment by mort3za** [comment]
Although I would like to move these static texts to somewhere in API, they can be inside the custom property.

**Comment by paulchrisluke** [comment]
Correct text: 
Shinta Mani Wild is the full package - in every sense of the word. Our rates are inclusive of a round trip private car transfer to/from Phnom Penh or Sihanoukville Airport and vicinity, as well as your personal Bensley Butler, all meals and beverages, privately guided activities to explore the Cardamom forest, luxury spa treatments, WiFi throughout the camp and of course daily laundry service.  


> Also, I need the Cloudinary link of those 2 images in the cards.

all inclusive: https://res.cloudinary.com/ddwsbpkzk/image/upload/v1567747072/Shinta%20Mani%20Wild/Tents/All_Inclusive_-_Tent_Page_Shinta_Mani_Wild_kdfq4g.jpg

Personal Butler: 
https://res.cloudinary.com/ddwsbpkzk/image/upload/v1568948083/Shinta%20Mani%20Wild/Tents/Head_Butler_Mac_-_Shinta_Mani_Wild_xxc4i9.jpg
