### ISSUE TITLE
add fade to hover effect that autoplays video

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#73]
right now our hover effect is very fast (awesome) but maybe jarring. Add a slight delay to the hover effect and a fade transition like https://www.youtube.com/

**Comment by mort3za** [comment]
copy from merge request:

> A note on video previews: The size of videos (for preview) is big, we should reduce it to under 250KB, cuz we want to show it immediately.

**Comment by paulchrisluke** [comment]
We will provide cloudinary links to database. 

Currently previews flash white before playing videos, it should be flashing a darker gray.
