### ISSUE TITLE
Like button data Link to Postgres

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#81]
That like <3 button needs to send like data back to postgres. We will send what the user likes to management on booking. Later, we are going to use like's to organize the site content (if a user likes food stuff, show food images).

If that is too complicated to do on first pass, we can icebox the data transfer stuff and simply allow it to be colored.

https://github.com/whynotearth/shinta-mani-wild/issues/20#issue-482142336

**Comment by mort3za** [comment]
I can't do it right now, because stories have no `id` and it seems we have no API to send the likes data.

**Comment by paulchrisluke** [comment]
That’s ok, can we hide the heart for now till we get it?

**Comment by mort3za** [comment]
Yeah, sure.

**Comment by paulchrisluke** [comment]
hid the like button, moving to backlog until api is ready
