### ISSUE TITLE
Wildlife Alliance Renamed

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#90]
The Wildlife Alliance Tent page has been renamed to the "Two Bedroom Tent" 

URL slug has changed to two-bedroom-tent and updated in database

- Make sure all associated page titles are changed to 2 bedroom tent (units are still named "wildlife alliance and jungle capsule")
- Change nav 
![image](https://user-images.githubusercontent.com/5694308/65298263-10348c00-db95-11e9-8c27-01b82cbc95d2.png)

**Comment by mort3za** [comment]
"Wildlife Alliance" text is used in home texts:  

> Shinta Mani Wild is a radical new fusion of world-class design, hospitality and conservation. The camp was born when world-renowned designer Bill Bensley identified an unprotected, 350-hectare wildlife corridor – and set out to save it from poaching, mining and logging. Sustainability informs everything we do, hence our partnership with the **Wildlife Alliance** (whose rangers have an onsite station), and our resident naturalists, who assist our chef. The Shinta Mani Foundation...

> Shinta Mani Wild is a radical new fusion of world-class design, hospitality and conservation. The camp was born when world-renowned designer Bill Bensley identified an unprotected, 350-hectare wildlife corridor – and set out to save it from poaching, mining and logging. Sustainability informs everything we do, hence our partnership with the **Wildlife Alliance** (whose rangers have an onsite station), and our resident naturalists, who assist our chef. The Shinta Mani Foundation spearheads our conservation and community outreach programmes.

Send the updated text if it's necessary, please.

> units are still named "wildlife alliance and jungle capsule"
This is in use in booking flow, yeah?

**Comment by mort3za** [comment]
btw, seems first text block is incomplete: **and our resident naturalists, who assist our chef. The Shinta Mani Foundation...**

**Comment by paulchrisluke** [comment]
> "Wildlife Alliance" text is used in home texts:
> 
> > Shinta Mani Wild is a radical new fusion of world-class design, hospitality and conservation. The camp was born when world-renowned designer Bill Bensley identified an unprotected, 350-hectare wildlife corridor – and set out to save it from poaching, mining and logging. Sustainability informs everything we do, hence our partnership with the **Wildlife Alliance** (whose rangers have an onsite station), and our resident naturalists, who assist our chef. The Shinta Mani Foundation...
> 
Wildlife alliance here is the name of the organization, should be ok. 

But you're right, it does seem incomplete. I'll give you the new copy in a separate issue

The two tents (wildlife alliance and jungle capsule) together are called the 2 bedroom tent. That should be reflected in the booking flow, yes
