### ISSUE TITLE
Tent Page missing Nav Button

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/shinta-mani-wild#96]
All pages on site have new view tents button
![image](https://user-images.githubusercontent.com/5694308/65367335-e42f0e80-dc59-11e9-8fa9-a7baa634a4c2.png)

Tent page is missing new button, have it say "select tent" instead
![image](https://user-images.githubusercontent.com/5694308/65367289-21df6780-dc59-11e9-84df-10cdefbd101e.png)

On click this button will scroll down to this area to encourage tent selection
![image](https://user-images.githubusercontent.com/5694308/65367351-353f0280-dc5a-11e9-82a8-2b626cb35204.png)

**Comment by mort3za** [comment]
There is a condition on the "view tents" button in PageHeader.vue file:  
```
v-if="isViewTentsVisible"
```
It hides "view tents" button in `/tents` page.

**Comment by SquidwardHill** [comment]
Thank you!
